## python List 的特点,创建numpy数组和矩阵


In [1]:
import numpy

In [2]:
numpy.__version__

'1.15.1'

In [3]:
import numpy as np
L=[i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
L[5]="machine learning"
L


[0, 1, 2, 3, 4, 'machine learning', 6, 7, 8, 9]

In [5]:
import array
arr=array.array('i',[i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## numpy.array

In [6]:
nparr=np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
nparr.dtye

AttributeError: 'numpy.ndarray' object has no attribute 'dtye'

In [8]:
nparr.dtype

dtype('int32')

## 其他创建numpy.array的方法

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(10).dtype

dtype('float64')

In [11]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.zeros(((3,5)))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.zeros(shape=(3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [14]:
np.ones(shape=(3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.full(shape=(3,5),fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

## arrange 

In [16]:
[i for i in range(0,20,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## linspace

In [23]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [24]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

## random

In [25]:
np.random.randint(0,10)

2

In [26]:
np.random.randint(0,10,10)

array([6, 4, 7, 1, 0, 9, 4, 9, 2, 3])

In [27]:
np.random.randint(0,1,10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## 随机生成10个4到8之间的整数，一位数组、二维数组

In [4]:
np.random.randint(4,8,size=10)

array([4, 4, 5, 7, 6, 5, 5, 6, 4, 7])

In [6]:
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 5, 4],
       [4, 7, 6, 5, 4],
       [4, 5, 5, 6, 5]])

## 随机种子

In [7]:
np.random.seed(666)
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [8]:
np.random.seed(666)
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [9]:
np.random.seed()
np.random.randint(4,8,size=(3,5))

array([[5, 5, 7, 4, 7],
       [6, 5, 5, 5, 6],
       [7, 7, 6, 7, 6]])

In [12]:
np.random.seed()
np.random.randint(4,8,size=(3,5))

array([[5, 4, 6, 5, 5],
       [4, 5, 6, 7, 4],
       [6, 4, 6, 4, 7]])

In [13]:
np.random.random()

0.7491672517939241

In [14]:
np.random.random(10)

array([0.08957185, 0.82323269, 0.68619628, 0.34618905, 0.84934294,
       0.63415156, 0.8445831 , 0.86973789, 0.40510627, 0.37413049])

In [15]:
np.random.random(size=(3,5))

array([[0.90073341, 0.06004427, 0.26262058, 0.54092252, 0.53095885],
       [0.60759916, 0.92692017, 0.01674437, 0.71159606, 0.24017019],
       [0.43382522, 0.66368027, 0.33774121, 0.99350306, 0.15285791]])

## 随机生成满足正太分布的数，第一个参数为均值，第二个参数为方差，第三个参数为大小

In [16]:
np.random.normal()

1.441918674973916

In [17]:
np.random.normal(10,100)

135.02756805009736

In [18]:
np.random.normal(0,1,(3,5))

array([[-0.69166256, -1.45253544, -0.70681084,  0.11461568,  0.01435055],
       [ 0.26395213,  0.76575205,  0.81355616,  0.00880567, -1.1958956 ],
       [ 0.4093381 , -0.9444056 ,  0.68650129,  0.23098359, -1.60288706]])

In [21]:
np.random.normal?

In [23]:
np.random?

In [24]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap