## 比较和fancyindexing

In [1]:
import numpy as np
x=np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x[3]

3

In [3]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [4]:
x[3:9:2]

array([3, 5, 7])

In [6]:
[x[3],x[5],x[8]]

[3, 5, 8]

In [7]:
ind=[3,5,8]
x[ind]

array([3, 5, 8])

In [8]:
ind=np.array([[0,2],[1,3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [9]:
X=x.reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
row=np.array([0,1,2])
col=np.array([1,2,3])
X[row,col]

array([ 1,  6, 11])

In [11]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
x<3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])